### PR TITLE
Add github action to build and check docs source

### PR DESCRIPTION
**Pull request by gdevenyi**

### CODE REVIEW

**Comment by surchs** [comment]
thanks @gdevenyi, this looks interesting. What's the use case for us? I think we have build hooks directly from readthedocs. Is this for CI integration?

**Comment by gdevenyi** [comment]
This is to do a build to bubble up errors such as those that came up in #22 in the PR interface:
https://github.com/marketplace/actions/sphinx-build

**Comment by surchs** [comment]
I see. That's a good idea!

**Comment by gdevenyi** [comment]
Hurrah, passing build with no warnings or errors. :+1:

**Review by surchs — APPROVED** [review]
Looks good to me! :tada:

**Pull request merged**
