### PR TITLE
Update requirement versions and Python to 3.10

### PR DESCRIPTION
**Pull request by joshunrau**

### CODE REVIEW

**Comment by gdevenyi** [comment]
Wrong capitalization for Sphinx

**Comment by joshunrau** [comment]
Actually, the correct package name is Sphinx (see https://pypi.org/project/Sphinx/). Although pip is not case sensitive, so for practical reasons it makes no difference, the name was technically incorrect.

**Comment by gdevenyi** [comment]
> Although pip is not case sensitive, so for practical reasons

This is actually really smart to avoid namesquatting

**Comment by joshunrau** [comment]
Yeah. If this wasn't the case I imagine "Numpy" would be a great package name for people developing malware.

**Pull request merged**
